### ISSUE TITLE
Clicking '-' on a skill will increase the skill instead

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#116]
Currently there is some major errors happening with the checks that are around skill purchasing. 
if a player tries to decrement a skill below 0 it will cause the server to throw the following error
```Internal Server Error: /en/characters/addskill/
Traceback (most recent call last):
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1690, "BIGINT UNSIGNED value is out of range in '(`talesofvalor_test`.`characters_character`.`cp_spent` + -(1))'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\timtp\OneDrive\Documents\GitHub\CodeCrow\talesofvalor_python\talesofvalor\characters\views.py", line 362, in post
    character.save()
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\sql\compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\timtp\.virtualenvs\talesofvalor_python-BlV08g-X\lib\site-packages\django\db\backends\mysql\base.py", line 78, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1690, "BIGINT UNSIGNED value is out of range in '(`talesofvalor_test`.`characters_character`.`cp_spent` + -(1))'")
```
then when the player then clicks 'Update' and then goes back to edit their skill (or simply refreshes the page) the skill they tried to decrement will be instead increased. On top of that they will not have the CP deducted from their total. Continuing to try and decrement the same skill will continue to throw the above error, and the skill will further be increased on page refresh.

**Comment by CodeCrow** [comment]
Fixed in the newest Stage . . .
